#!/usr/bin/env bash
# setup_nanobanana.sh — install and configure the nanobanana MCP server for Gemini image generation
#
# What this does:
#   1. Checks for uv / uvx (installs if missing)
#   2. Prompts for your Gemini API key and writes it to .env
#   3. Adds .env to .gitignore
#   4. Creates .mcp.json with the nanobanana server config
#   5. Creates / updates .claude/settings.json with MCP permissions
#   6. Verifies uvx can reach nanobanana-mcp-server
#
# Usage:
#   bash scripts/setup_nanobanana.sh
#   bash scripts/setup_nanobanana.sh --key AIzaSy...   (pass key non-interactively)
#
# Requirements:
#   - macOS or Linux
#   - curl (for uv install if needed)
#   - An active internet connection
#
# After running this script:
#   set -a && source .env && set +a   # export key in current terminal
#   claude                             # open Claude Code — nanobanana auto-starts

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}→${RESET} $*"; }
success() { echo -e "${GREEN}✓${RESET} $*"; }
warn()    { echo -e "${YELLOW}⚠${RESET} $*"; }
error()   { echo -e "${RED}✗${RESET} $*" >&2; }
header()  { echo -e "\n${BOLD}$*${RESET}"; }

# ── Parse args ────────────────────────────────────────────────────────────────
KEY_FLAG=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --key) KEY_FLAG="${2:?'--key requires a value'}"; shift 2 ;;
    -h|--help)
      grep '^#' "$0" | head -n 20 | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) error "Unknown argument: $1"; exit 1 ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

header "nanobanana MCP Setup"
echo "Working directory: $REPO_ROOT"

# ── Step 1: uv / uvx ─────────────────────────────────────────────────────────
header "Step 1 — Checking uv / uvx"
if command -v uvx &>/dev/null; then
  UVX_VER="$(uvx --version 2>&1 | head -1)"
  success "uvx already installed: $UVX_VER"
else
  warn "uvx not found — installing uv now"
  if ! command -v curl &>/dev/null; then
    error "curl is required to install uv. Install curl first."
    exit 1
  fi
  curl -LsSf https://astral.sh/uv/install.sh | sh
  # Source the new path without requiring a new shell
  export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"
  if command -v uvx &>/dev/null; then
    success "uv installed: $(uvx --version 2>&1 | head -1)"
  else
    error "uv install may have succeeded but uvx is not yet in PATH."
    echo "  Run: source \$HOME/.cargo/env  (or open a new terminal)"
    echo "  Then re-run this script."
    exit 1
  fi
fi

# ── Step 2: Gemini API key ────────────────────────────────────────────────────
header "Step 2 — Gemini API Key"
ENV_FILE="${REPO_ROOT}/.env"
ENV_EXAMPLE="${REPO_ROOT}/.env.example"

if [[ -n "$KEY_FLAG" ]]; then
  GEMINI_KEY="$KEY_FLAG"
  info "Using key from --key flag"
elif [[ -f "$ENV_FILE" ]] && grep -q "^GEMINI_API_KEY=AIza" "$ENV_FILE" 2>/dev/null; then
  GEMINI_KEY="$(grep '^GEMINI_API_KEY=' "$ENV_FILE" | cut -d'=' -f2)"
  success "GEMINI_API_KEY already in .env — skipping prompt"
else
  echo ""
  echo "  Get a free key at: https://aistudio.google.com/apikey"
  echo "  (Free tier: 15 req/min, 1500 req/day)"
  echo ""
  read -rp "  Paste your GEMINI_API_KEY (starts with AIza...): " GEMINI_KEY
  if [[ -z "$GEMINI_KEY" ]]; then
    error "No key entered. Exiting."
    exit 1
  fi
fi

# Write .env
if [[ -f "$ENV_FILE" ]]; then
  # Update existing key line, or append
  if grep -q "^GEMINI_API_KEY=" "$ENV_FILE"; then
    # Replace the line in-place (compatible with macOS sed)
    sed -i.bak "s|^GEMINI_API_KEY=.*|GEMINI_API_KEY=${GEMINI_KEY}|" "$ENV_FILE"
    rm -f "${ENV_FILE}.bak"
  else
    echo "GEMINI_API_KEY=${GEMINI_KEY}" >> "$ENV_FILE"
  fi
else
  # Create fresh .env from example if it exists, else minimal
  if [[ -f "$ENV_EXAMPLE" ]]; then
    cp "$ENV_EXAMPLE" "$ENV_FILE"
    sed -i.bak "s|^GEMINI_API_KEY=.*|GEMINI_API_KEY=${GEMINI_KEY}|" "$ENV_FILE"
    rm -f "${ENV_FILE}.bak"
  else
    {
      echo "# Auto-generated by setup_nanobanana.sh"
      echo "GEMINI_API_KEY=${GEMINI_KEY}"
    } > "$ENV_FILE"
  fi
fi
success ".env written with GEMINI_API_KEY"

# ── Step 3: .gitignore ────────────────────────────────────────────────────────
header "Step 3 — .gitignore"
GITIGNORE="${REPO_ROOT}/.gitignore"
ADDED_GITIGNORE=false
for pattern in ".env" ".env.*" "*.env"; do
  if ! grep -qxF "$pattern" "$GITIGNORE" 2>/dev/null; then
    echo "$pattern" >> "$GITIGNORE"
    ADDED_GITIGNORE=true
  fi
done
if $ADDED_GITIGNORE; then
  success "Added .env patterns to .gitignore"
else
  success ".gitignore already excludes .env files"
fi

# ── Step 4: .mcp.json ─────────────────────────────────────────────────────────
header "Step 4 — .mcp.json"
MCP_JSON="${REPO_ROOT}/.mcp.json"
if [[ -f "$MCP_JSON" ]] && grep -q '"nanobanana"' "$MCP_JSON"; then
  success ".mcp.json already has nanobanana — skipping"
else
  if [[ -f "$MCP_JSON" ]]; then
    warn ".mcp.json exists but doesn't have nanobanana. Backing up to .mcp.json.bak"
    cp "$MCP_JSON" "${MCP_JSON}.bak"
    # Inject nanobanana into existing file using Python (handles any JSON shape)
    python3 - "$MCP_JSON" <<'PYEOF'
import json, sys
path = sys.argv[1]
with open(path) as f:
    data = json.load(f)
data.setdefault("mcpServers", {})["nanobanana"] = {
    "command": "uvx",
    "args": ["nanobanana-mcp-server@latest"],
    "env": {"GEMINI_API_KEY": "${GEMINI_API_KEY}"}
}
with open(path, "w") as f:
    json.dump(data, f, indent=2)
print("ok")
PYEOF
  else
    cat > "$MCP_JSON" <<'JSON'
{
  "mcpServers": {
    "nanobanana": {
      "command": "uvx",
      "args": ["nanobanana-mcp-server@latest"],
      "env": {
        "GEMINI_API_KEY": "${GEMINI_API_KEY}"
      }
    }
  }
}
JSON
  fi
  success ".mcp.json configured"
fi

# ── Step 5: .claude/settings.json ─────────────────────────────────────────────
header "Step 5 — .claude/settings.json (MCP permissions)"
CLAUDE_DIR="${REPO_ROOT}/.claude"
SETTINGS="${CLAUDE_DIR}/settings.json"
mkdir -p "$CLAUDE_DIR"

REQUIRED_PERMS=(
  "mcp__nanobanana__generate_image"
  "mcp__nanobanana__upload_file"
  "mcp__nanobanana__show_output_stats"
)

if [[ -f "$SETTINGS" ]]; then
  # Add permissions with Python (handles existing JSON safely)
  python3 - "$SETTINGS" "${REQUIRED_PERMS[@]}" <<'PYEOF'
import json, sys
path, *perms = sys.argv[1:]
with open(path) as f:
    data = json.load(f)
allow = data.setdefault("permissions", {}).setdefault("allow", [])
added = []
for p in perms:
    if p not in allow:
        allow.append(p)
        added.append(p)
with open(path, "w") as f:
    json.dump(data, f, indent=2)
if added:
    print(f"Added permissions: {', '.join(added)}")
else:
    print("All permissions already present")
PYEOF
else
  python3 -c "
import json, sys
perms = sys.argv[1:]
data = {'permissions': {'allow': perms}}
print(json.dumps(data, indent=2))
" "${REQUIRED_PERMS[@]}" > "$SETTINGS"
fi
success ".claude/settings.json updated"

# ── Step 6: Verify uvx can reach nanobanana ───────────────────────────────────
header "Step 6 — Verifying nanobanana is reachable"
info "Running: uvx nanobanana-mcp-server@latest --version (may download on first run)..."
if timeout 90 uvx nanobanana-mcp-server@latest --version &>/dev/null; then
  success "nanobanana-mcp-server reachable"
else
  warn "Could not verify nanobanana-mcp-server. It may still work — first run can be slow."
  warn "If image generation fails, check your internet connection and try again."
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}Setup complete!${RESET}"
echo ""
echo "Next steps:"
echo ""
echo "  1. Export the API key in your terminal:"
echo -e "     ${CYAN}set -a && source .env && set +a${RESET}"
echo ""
echo "  2. Open Claude Code from the same terminal:"
echo -e "     ${CYAN}claude${RESET}"
echo ""
echo "  3. Test image generation:"
echo "     Generate a test image: a simple blue square, save to outputs/test.png"
echo ""
echo "  First image may take 30-60s while uvx downloads the server."
echo "  Subsequent images: 2-4 seconds each."
echo ""
echo "  Full setup guide: references/image-generation.md"
